<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>22716c75-1b02-4bd0-91cc-17fb8e7237f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[3]/div/div/div[6]/div/div/a/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Sakit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;Sakit&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>34aed4e4-c599-4136-8175-669114136995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sakit</value>
      <webElementGuid>32807d77-96ff-46dd-9dd1-7e7b211badd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>8d491355-4958-4e14-a54c-2fe5ff1eefe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fsick.svg&amp;w=640&amp;q=75 640w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fsick.svg&amp;w=750&amp;q=75 750w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fsick.svg&amp;w=828&amp;q=75 828w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fsick.svg&amp;w=1080&amp;q=75 1080w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fsick.svg&amp;w=1200&amp;q=75 1200w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fsick.svg&amp;w=1920&amp;q=75 1920w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fsick.svg&amp;w=2048&amp;q=75 2048w, /_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fsick.svg&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>39a88290-8e9c-49f7-9d5a-32c0c39c9bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fsick.svg&amp;w=3840&amp;q=75</value>
      <webElementGuid>bb043bfa-9c2b-4457-acb6-c1a310f416c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>0b8431d5-e970-45e4-9ec0-5b3eea2e4c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>responsive</value>
      <webElementGuid>3bb62e08-5d1d-4d1e-9d7e-a4afb0f57fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthSm css-ewqxmf&quot;]/div[@class=&quot;MuiBox-root css-19n8dai&quot;]/div[@class=&quot;MuiBox-root css-wmurvm&quot;]/div[@class=&quot;MuiBox-root css-1dovkig&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-isbt42&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-3 MuiGrid-grid-sm-3 css-4xkoi8&quot;]/div[@class=&quot;MuiBox-root css-7wh13m&quot;]/div[@class=&quot;MuiBox-root css-zg1vud&quot;]/a[@class=&quot;user__menu__item&quot;]/div[@class=&quot;MuiBox-root css-11uwjng&quot;]/span[1]/img[1]</value>
      <webElementGuid>acb1105a-8aee-477b-8bef-dfd7fff9be47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/div/div/div[6]/div/div/a/div/span/img</value>
      <webElementGuid>b2fb9142-1362-4c9f-b95e-062513eb8a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sakit']</value>
      <webElementGuid>7f807f8d-4fa3-4ed7-b39a-b9dd048ec8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/a/div/span/img</value>
      <webElementGuid>368aa437-a227-40fd-9802-673dda2044d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Sakit' and @src = '/_next/image?url=%2Fstatic%2Fimages%2Ficons%2Fsick.svg&amp;w=3840&amp;q=75']</value>
      <webElementGuid>1ae2077d-672f-4be1-8498-7cab28aba337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
