<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Info Cuti</name>
   <tag></tag>
   <elementGuidId>a4cd2be4-ef6b-4400-9c76-66bab44dc002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mui-p-79547-T-infoCuti']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-p-79547-T-infoCuti</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Info Cuti&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6bfbec3-a5d8-47b4-bc4d-3bb8cc7b2a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary css-1sh52gn</value>
      <webElementGuid>9d4195dc-ff40-4298-beae-eef0204800b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>68bda375-6f35-410f-9ad7-6ac1dc608bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c774e44a-8e4e-4417-8e60-8237fb4d5d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>5dfd7e1b-3033-4d74-9cd9-9bd2ca0dd005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>30ed34ea-ff37-4bbe-a715-ef620fd610f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mui-p-79547-P-infoCuti</value>
      <webElementGuid>044776ce-4e6b-4751-8815-63f30aaa3efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-p-79547-T-infoCuti</value>
      <webElementGuid>ccb5c71b-5812-4cc0-a373-ca2340605cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Info Cuti</value>
      <webElementGuid>3ba25143-59f5-4009-8d9f-9dca05b7259a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-p-79547-T-infoCuti&quot;)</value>
      <webElementGuid>70fc1745-2016-4a4b-9e50-562b85904cce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mui-p-79547-T-infoCuti']</value>
      <webElementGuid>1fdb06ed-54bb-4a08-94be-ffd2b7326261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Cuti'])[1]/following::button[1]</value>
      <webElementGuid>11a25ce1-2591-47dc-a332-cd8de9762a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tipe Cuti'])[1]/preceding::button[1]</value>
      <webElementGuid>2cff7ce4-9e5f-4385-8b90-3ba8452d7873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tipe Absen'])[1]/preceding::button[1]</value>
      <webElementGuid>44513d8f-9832-406d-af92-466b901bea14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Info Cuti']/parent::*</value>
      <webElementGuid>a9498a79-c3e4-4952-9dea-eed34a8842ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>eb2e7ce9-dc57-42d3-8fd6-098245edabbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'mui-p-79547-T-infoCuti' and (text() = 'Info Cuti' or . = 'Info Cuti')]</value>
      <webElementGuid>513b8b67-032d-4a57-8a60-c4e497940fcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
