<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalCuti</name>
   <tag></tag>
   <elementGuidId>9d4c3d13-4fdb-41fb-ad2a-ea692691aeb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mui-p-79547-P-infoCuti']/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.MuiList-root.MuiList-padding.css-1ontqvh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Total Cuti: 0Total cuti tersedia: Total cuti bersama: 0Total cuti disetujui: 0To&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>88e3a24f-4e63-49c8-affe-973899c28915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiList-root MuiList-padding css-1ontqvh</value>
      <webElementGuid>486a5732-15c2-4270-a6f2-4ef5ca757ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total Cuti: 0Total cuti tersedia: Total cuti bersama: 0Total cuti disetujui: 0Total cuti yang sedang diajukan: 0Total sisa cuti (Annual): 0</value>
      <webElementGuid>307edbbe-7213-471d-824c-c19a0527cb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-p-79547-P-infoCuti&quot;)/ul[@class=&quot;MuiList-root MuiList-padding css-1ontqvh&quot;]</value>
      <webElementGuid>c38c74c6-035a-4fb5-8e53-8bae26c5266e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mui-p-79547-P-infoCuti']/ul</value>
      <webElementGuid>89574b11-8040-4379-8555-084fe96acb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info Cuti'])[1]/following::ul[1]</value>
      <webElementGuid>740d7685-b869-4510-bd91-6044d275bd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Cuti'])[1]/following::ul[1]</value>
      <webElementGuid>83660f51-df70-4ce8-b837-c860e773a005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>4e697d32-0b35-45b5-9d91-63f92609d7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'Total Cuti: 0Total cuti tersedia: Total cuti bersama: 0Total cuti disetujui: 0Total cuti yang sedang diajukan: 0Total sisa cuti (Annual): 0' or . = 'Total Cuti: 0Total cuti tersedia: Total cuti bersama: 0Total cuti disetujui: 0Total cuti yang sedang diajukan: 0Total sisa cuti (Annual): 0')]</value>
      <webElementGuid>38abfe9e-5d7b-44e1-867f-559917ad8563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
