<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tanggal</name>
   <tag></tag>
   <elementGuidId>b85c2e56-0bd6-4852-8eec-87be2fe607db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6.MuiTypography-root.MuiTypography-h6.css-1gtt4lb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[3]/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=checkbox[name=&quot;AB Anif Biantoro 24 Sep 2024 25 Sep 2024 - 25 Sep 2024 Sayurbox - - Cuti persalinan (3 bulan) Testing 3 (Ajuan di tanggal sama) Lihat Selengkapnya Dibatalkan Notes : Lihat Selengkapnya&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>3b48d018-a42f-412e-90a5-e507df7e1771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h6 css-1gtt4lb</value>
      <webElementGuid>fd61e0e9-03e8-4838-bad5-4bd6ec6d2950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24 Sep 2024</value>
      <webElementGuid>b5f27090-ab41-4f1f-a4cc-4fa0d29b9222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-10f63sf&quot;]/div[@class=&quot;css-11qbmxu&quot;]/div[@class=&quot;MuiContainer-root css-1p62yps&quot;]/div[@class=&quot;MuiBox-root css-76jx17&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-1d3bbye&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-lg-12 css-15j76c0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-oim7up&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 css-1d88nt7&quot;]/div[@class=&quot;MuiTableContainer-root css-kge0eu&quot;]/table[@class=&quot;MuiTable-root MuiTable-stickyHeader css-o1eexh&quot;]/tbody[@class=&quot;MuiTableBody-root css-1xnox0e&quot;]/tr[@class=&quot;MuiTableRow-root MuiTableRow-hover css-lry5m7&quot;]/td[@class=&quot;MuiTableCell-root MuiTableCell-body MuiTableCell-sizeSmall css-1udpcma&quot;]/h6[@class=&quot;MuiTypography-root MuiTypography-h6 css-1gtt4lb&quot;]</value>
      <webElementGuid>1a7c4f95-710d-452e-9634-94588ff2e2d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div[2]/div/div/div/table/tbody/tr/td[3]/h6</value>
      <webElementGuid>e75d1fe5-dbcc-46ee-9e28-37a324180738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anif Biantoro'])[1]/following::h6[1]</value>
      <webElementGuid>e4cd0168-a263-4cf7-a145-66202c8e503c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AB'])[1]/following::h6[2]</value>
      <webElementGuid>dece070c-1923-4a23-8c34-cb3647516cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sayurbox'])[1]/preceding::h6[2]</value>
      <webElementGuid>9b7dc1e7-f356-454a-a2d3-79e281e1ef66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::h6[3]</value>
      <webElementGuid>2dd00f6d-149d-4820-9de2-4070e12cdc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='24 Sep 2024']/parent::*</value>
      <webElementGuid>61490ee5-d88e-46f0-8f25-2793f5bae73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/h6</value>
      <webElementGuid>3715ee5e-9760-4530-8899-af2918d4559b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = '24 Sep 2024' or . = '24 Sep 2024')]</value>
      <webElementGuid>3258b975-2376-4df6-84bd-c6b616739c79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
